[package]
name = "royal_agents"
version = "0.0.1"

[addresses]
royal_agents = "_"

[dev-addresses]
royal_agents = "0xBEEF"

[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "movement" }
AptosStdlib = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "movement" }
AptosTokenObjects = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects", rev = "movement" }
